name: C++ Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GCC
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Set up Python to install GCC

      - name: Build and Run C++ program
        run: |
          g++ -o main main.cpp
          ./main
