name: Build and Run C++ Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t my_cpp_app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Replace with your Docker Hub username
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # Use the secret name where the PAT is stored

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my_cpp_app ${{ secrets.DOCKER_USERNAME }}/my_cpp_app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my_cpp_app:latest
